[build]
  publish = "dist"
  command = "bin/build"
[[redirects]]
  from = "/"
  to = "/vm-production-chrome.zip"
[[redirects]]
  from = "/prod"
  to = "/vm-production-chrome.zip"
[[redirects]]
  from = "/dev"
  to = "/vm-development-chrome.zip"
[[redirects]]
  from = "/prod-xpi"
  to = "/vm-production-firefox.xpi"
[[redirects]]
  from = "/dev-xpi"
  to = "/vm-development-firefox.xpi"
